fusion-energy/paramak

.github/workflows/python-publish.yml
setup.py

A tiny change that makes use of pypi tokens instead of usernames and passwords. The advantage is One less github secret and limited access to pypi. I also enabled the github action again so when this is merged to main we should get an updated pip install

using token instead of user/pass

---

.github/workflows/python-publish.yml
setup.py

This change to the python publish CI automates the version tagging of the pypi package as proposed by @RemDelaporteMathurin 
It makes use of the example [here ](https://github.com/grst/python-ci-versioneer/blob/master/LICENSE) with small adaptations discussed [here](https://github.com/openmc-data-storage/openmc_data_to_json/issues/22)
I've tested the yml file with a mini release and it found the version number correctly https://github.com/fusion-energy/paramak/actions/runs/1044561332
This should save use a decent amount of time each release and remove the need for those "bump version commits" moving forwards

added python-ci-versioneer

---

docs/source/paramak.parametric_components.rst

This adds another 3d interactive shape to the docs. The example for this particular shape came from the examples folder [here](https://github.com/fusion-energy/paramak/blob/main/examples/example_parametric_components/make_firstwall_for_neutron_wall_loading.ipynb).
This is one of the many PRs that will be needed to close issue #30
I tested this by building the docs locally with sphinx. The 3d model didn't appear locally but[ it does on the automated readTheDocs build](https://paramak--31.org.readthedocs.build/en/31/paramak.parametric_components.html#poloidalsegmenter) that gets trigger for every PR
The status of the read the docs builds can be found for each PR, here is the one for this PR
[readTheDocs build for this PR](https://readthedocs.org/projects/paramak/builds/14271782/)
```
cd …
```

added 3d shape to docs for PoloidalSegmenter

---

paramak/parametric_components/center_column_cylinder.py
tests/test_parametric_components/test_CenterColumnShieldCylinder.py

Allows the CenterColumnShieldCylinder to be shifted vertically using a new argument called ```center_height``` which defaults to 0
The following image can now be made with code like this
```python
import paramak
inner_vessel = paramak.CenterColumnShieldCylinder(
inner_radius=3,
outer_radius=3.3,
height=5,
color=(0,0,1),
center_height=0
)
inner_vessel2 = paramak.CenterColumnShieldCylinder(
inner_radius=3,
outer_radius=3.3,
height=5,
center_height=-6,
color=(1,0,0)
)
inner_vessel3 = paramak.CenterColumnShieldCylinder(
inner_radius=3,
outer_radius=3.3,
height=5,
center_height=6,
color=(0,1,0)
)
r = paramak.Reactor([inner_vessel, inner_vessel2, inner_vessel3])
r.show()
```

Adding center point to center column cylinder

---

paramak/parametric_components/inner_tf_coils_flat.py
tests/test_parametric_components/test_InnerTfCoilsFlat.py

As discussed in #53 the inner_radius can not be set to 0. This PR adds a special case to the InnerTfCoilsFlat to allow radius 0 shapes.

added option for zero inner radius

---

Dockerfile
paramak/reactor.py
paramak/shape.py
tests/test_parametric_shapes/test_ExtrudeStraightShape.py
tests/test_reactor.py

This PR adds ```.name``` attributes to the Reactor class that returns all the names of the shapes.
```reactor.material_tags()``` has been renamed ``` ```reactor.material_tag()``` to be consistent with the Shape class
also allows keyword ```allow_repeat``` to b passed to ```reactor.material_tag()``` if one just wants to know the set() of tags
extra tests to cover the new code have been added

Adding names to reactor

---

Dockerfile
paramak/shape.py
tests/test_parametric_shapes/test_ExtrudeStraightShape.py
tests/test_shape.py

Linked to #81.
This PR allows user to define the workplane from a cadquery.Plane object, which is defined by an origin point and a normal vector.
This normal vector is then the extrusion vector.
**Usage**
```python
import paramak
from cadquery import Plane
points = [
(0, 0),
(1, 0),
(1, 1),
(0, 1)
]
shape_1 = paramak.ExtrudeStraightShape(points=points, distance=1)
normal_vec = (1, 1, 1)
workplane = Plane(origin=(0, 0, 0), xDir=(-1, 1, 0), normal=normal_vec)
shape_2 = paramak.ExtrudeStraightShape(
points=points, distance=1,
workplane=workplane,
rotation_axis='X')
shape_1.export_stl('non_rotated.stl')  # white
shape_2.export_stl('rotated.stl')  # red
```
_Put an `x` in the boxes that apply. …

Shape.workplane can now accept a cadquery.Plane object

---

paramak/reactor.py
paramak/shape.py
tests/test_parametric_reactors/test_eu_demo_2015_reactor.py
tests/test_parametric_reactors/test_iter_reactor.py
tests/test_parametric_reactors/test_sparc_2020_reactor.py
tests/test_parametric_reactors/test_submersion_tokamak.py
tests/test_reactor.py

This PR changes the default state to False for the ```inculde_graveyard``` in ```export_stp```, ```export_stl``` and ```export_neutronics_description``` 
As we are now using CSG surfaces for the graveyard in the ```openmc-dagmc-wrapper``` the main use case no longer requires a graveyard.
This has other benefits such as improved visualisation, less time needed to make geometry (make graveyard is the slowest part)
A graveyard can still be made by anyone requiring a graveyard by setting ```include_graveyard``` to true

export graveyard now defaults to false

---

.gitignore
README.md
docs/source/index.rst
paramak/parametric_components/toroidal_field_coil_round_corners.py
paramak/parametric_reactors/cylinder_reactor.py
paramak/reactor.py
paramak/shape.py
tests/test_parametric_shapes/test_sweep_straight_shape.py

Adding ```paramak.Shape.export_brep()``` to the code. This allows a ```Shape``` to be exported. Currently reactors can't be exported in this format but perhaps this will happen in the future.
These two issues where useful when making this feature 
https://github.com/CadQuery/cadquery/issues/449
https://github.com/CadQuery/cadquery/issues/697

Adding brep export to shape

---

paramak/reactor.py

Adds default stp filenames for reactor.export_stp(). If filename is left as None then the shape.name will be used as the stem of the stp file. This makes it easier to export the stp file for a reactor when users don't nessecarily know the number or order of components in the reactor

adds default stp filenames based on name

---

paramak/reactor.py
tests/test_parametric_reactors/test_cylinder_reactor.py

As discussed in the cadquery issue https://github.com/CadQuery/cadquery/issues/449 it looks like is possible to merge surfaces in a brep file. This PR adds a ```merge``` option to the ```Reactor.export_brep()``` to test out the feature.

Adding merge option to brep export

---

paramak/reactor.py
tests/test_reactor.py

stp files were being exported with the name as None and saved as None.stp.
This PR adds a check when exporting stp and slt files using the Shape.name. Checks that the Shape.name is not None.

Adding check for name none

---

.github/workflows/docker_publish.yml
Dockerfile

Reduces the docker publish time by 1 min using docker layer caching
caching can be seeing in the gh action
https://github.com/fusion-energy/paramak/runs/4217202863?check_suite_focus=true
Followed this tutorial
https://evilmartians.com/chronicles/build-images-on-github-actions-with-docker-layer-caching

Docker layer caching

---

docs/source/parametric_components.rst
examples/example_parametric_components/make_components_other.ipynb
paramak/__init__.py
paramak/parametric_components/blanket_cutter_parallels.py
paramak/parametric_components/blanket_cutters_star.py
paramak/parametric_components/center_column_cylinder.py
paramak/parametric_components/extrude_hollow_rectangle.py
paramak/reactor.py
tests/test_parametric_components/test_extrude_hollow_rectangle.py

Adds a new parametric shape that is an extruded hollow rectangle
I still need to add tests and documentation to finish this PR

Adding extrude hollow reactangle

---

paramak/parametric_shapes/extruded_mixed_shape.py
paramak/reactor.py

adds a ```part_properties``` method to the ```Reactor``` class for use with the brep_part_finder package

Adding part properties for brep to h5m

---

setup.cfg

Adds a few lines to setup.cfg to inform flake8 to ignore convenience imports from __init__.py. 
Closes https://github.com/fusion-energy/paramak/issues/134

Ignore __init__.py imports with flake8

---

.github/workflows/ci_with_docker_build.yml
Dockerfile

Another potential way to avoid BuildKit, similar to https://github.com/fusion-energy/paramak/pull/159 and https://github.com/fusion-energy/paramak/pull/158, is to build a Python Wheel, copy only that and unit test requirements into the container, and install from there. The primary downside of this approach (if it works) is that the user must now pass the filename of a Python wheel as a --build-arg to docker (it may be possible to grab this from within the Dockerfile, but I'm not familiar enough with Docker ARGs to confirm). The upside is that it should result in a very lightweight container and solve the version inference problem.
This will require additional changes to `docker-publish.yml` before it's ready to merge, though I'll need to do some further reading before making those …

Avoid Docker BuiltKit by installing from wheel

---

.github/workflows/ci_with_docker_build.yml
Dockerfile
tests/test_version.py

This PR removes the need for --bind and BuildKit by passing in the paramak version number via the build-args. Also removes the need to copy the .git folder

avoiding builds tools: method get version number from CI

---

conda/meta.yaml
conda_build.sh
docs/source/index.rst
docs/source/install.rst
environment.yml
setup.cfg
tests/test_parametric_shapes/test_extrude_straight_shape.py
tests/test_reactor.py

pins the version of pyparsing to the same version that cadquery is pinning to.

pinned pyparsing ~= 2.4.7

---

.github/workflows/anaconda-publish-develop.yml
conda_dev/meta.yaml

This updates the conda build for the ```paramak_develop``` version of paramak
This is a version that makes use of the current cadquery master branch and has a few experimental features
One feature is the ability to export the geometry as a dagmc h5m file
This conda build is working locally so hopefully it will work on the github action

removed packages that are brought in already

---

paramak/reactor.py
paramak/shape.py
setup.cfg

Jupyter-Cadquery was recently updated and looks even better than before. Congrats to @bernhard-42 for continuing to develop this nice software. It is a great package that we should certainly try to keep making use of. A few changes to the import statement and show method are needed to work with the new v3.0.0 api for jupyter-cadquery
This PR is still not quite working in the dockerfile and I'm getting a error when trying to display the 3d model using jupyter-cadquery in jupyter lab.
So this PR is a working progress but I hope to get this working soon, I'm just in the process of reformatting my computer so hopefully I shall be up and running with a new system soon
```
Error displaying widget
<cad_viewer_widget.widget.CadViewer at 0x7f1e4ab8eaf0>
```
and other errors
```
> …
```

Changes to work with jupyter cadquery v3.0.0

---

paramak/parametric_shapes/extruded_circle_shape.py
paramak/parametric_shapes/extruded_mixed_shape.py
paramak/parametric_shapes/extruded_spline_shape.py
paramak/parametric_shapes/extruded_straight_shape.py
paramak/parametric_shapes/rotate_circle_shape.py
paramak/parametric_shapes/rotate_mixed_shape.py
paramak/parametric_shapes/rotate_spline_shape.py
paramak/parametric_shapes/rotate_straight_shape.py
paramak/parametric_shapes/sweep_circle_shape.py
paramak/parametric_shapes/sweep_mixed_shape.py
paramak/parametric_shapes/sweep_spline_shape.py
paramak/parametric_shapes/sweep_straight_shape.py
tests/test_parametric_shapes/test_extrude_straight_shape.py
tests/test_parametric_shapes/test_rotate_straight_shape.py
tests/test_parametric_shapes/test_sweep_mixed_shape.py
tests/test_parametric_shapes/test_sweep_straight_shape.py

These changes allow a translation to be added to an extruded shape.
behavior before:
it is not possible to translate a shape directly so this has to be done as a post process on the cadquery object
```
import paramak
extruded_straight = paramak.ExtrudeStraightShape(
points=[
(300, -300),
(400, 0),
(300, 300),
(400, 300),
(500, 0),
(400, -300),
],
distance=200
)
extruded_straight.solid = extruded_straight.solid.translate(200,0,0)
```
behavior afterwards:
now the shape can be translated when created
```
import paramak
extruded_straight = paramak.ExtrudeStraightShape(
points=[
(300, -300),
(400, 0),
(300, 300),
(400, 300),
(500, 0),
(400, -300),
],
distance=200,
translate(200,0,0)
)
```
To merge this in there are still a few outstanding tasks:
_Put an `x` in the boxes that apply. You can …

added option to translate shapes

---

docs/source/API-Reference.rst
examples/example_parametric_components/make_components_other.ipynb
paramak/__init__.py
paramak/parametric_components/circular_port.py
tests/test_parametric_components/test_circular_port.py

Adds a circular port parametric component that is a pipe with a flange. An svg image was made with and can be uploaded to the docs later
```
component.export_svg('/home/jshimwell/paramak/port.svg', projectionDir=(-0.1, -0.45, 1))
```

Adding circlar ports with flange gap option

---

paramak/reactor.py
paramak/shape.py
paramak/utils.py
tests/test_parametric_reactors/test_ball_reactor.py
tests/test_parametric_reactors/test_center_column_study_reactor.py
tests/test_parametric_reactors/test_eu_demo_2015_reactor.py
tests/test_parametric_reactors/test_flf_system_code_reactor.py
tests/test_parametric_reactors/test_iter_reactor.py
tests/test_parametric_reactors/test_segmented_blanket_ball_reactor.py
tests/test_parametric_reactors/test_single_null_ball_reactor.py
tests/test_parametric_reactors/test_single_null_submersion_tokamak.py
tests/test_parametric_reactors/test_sparc_2020_reactor.py
tests/test_parametric_reactors/test_submersion_tokamak.py
tests/test_parametric_shapes/test_extrude_straight_shape.py
tests/test_reactor.py
tests/test_utils.py

tidies up the utils import statements a little bit and moves the largest_dimension function to the utils.
this will allow largest_dimension to be called during the construction of solids to help find the height and radius when making a cutting wedge

added .bounding_box and refactored .largest_dimension

---

.github/workflows/auto_format_pep8.yml
.github/workflows/auto_lint.yml
paramak/parametric_components/constant_thickness_dome.py
paramak/parametric_components/dished_vacuum_vessel.py
paramak/parametric_reactors/flf_system_code_reactor.py
paramak/reactor.py
paramak/shape.py
paramak/utils.py
tests/test_parametric_components/test_constant_thickness_dome.py
tests/test_parametric_components/test_dished_vacuum_vessel.py
tests/test_utils.py

Changes the reactor to start at floor level, this makes comparison simulations with CSG easier and location of the neutron source easier

moved reactor to start from floor level

---

paramak/reactor.py
paramak/shape.py
tests_h5m/test_reactor_export_h5m.py
tests_h5m/test_rotate_straight_shape_export_h5m.py

As discussed in issue #233 this PR adds support for custom tags to be exported to dagmc h5m files.
TODO
add option to include the graveyard when exporting to dagmc geometry. I might need to rework the graveyard feature a bit before adding this

Adding tests for dagmc export to other codes

---

paramak/__init__.py
paramak/reactor.py
paramak/shape.py
paramak/utils.py
tests/test_parametric_reactors/test_center_column_study_reactor.py
tests/test_parametric_reactors/test_flf_system_code_reactor.py
tests/test_parametric_shapes/test_rotate_straight_shape.py
tests_h5m/test_reactor_export_h5m.py
tests_h5m/test_rotate_straight_shape_export_h5m.py

Work in progress. This PR will add the option of exporting the DAGMC file with a graveyard. This is useful for codes that don't yet support implicit graveyards or allow graveyards to be made from CSG cells.
I've added unit tests but need to add the functionality next

added graveyard tag tests

---

paramak/__init__.py
paramak/parametric_components/extrude_hollow_rectangle.py
paramak/parametric_components/hollow_cube.py
paramak/reactor.py
paramak/shape.py
paramak/utils.py
tests/test_parametric_components/test_extrude_hollow_cube.py
tests/test_parametric_reactors/test_ball_reactor.py
tests/test_parametric_reactors/test_center_column_study_reactor.py
tests/test_parametric_reactors/test_eu_demo_2015_reactor.py
tests/test_parametric_reactors/test_flf_system_code_reactor.py
tests/test_parametric_reactors/test_iter_reactor.py
tests/test_parametric_reactors/test_segmented_blanket_ball_reactor.py
tests/test_parametric_reactors/test_single_null_ball_reactor.py
tests/test_parametric_reactors/test_single_null_submersion_tokamak.py
tests/test_parametric_reactors/test_sparc_2020_reactor.py
tests/test_parametric_reactors/test_submersion_tokamak.py
tests/test_parametric_shapes/test_extrude_straight_shape.py
tests/test_reactor.py
tests/test_utils.py
tests_h5m/test_reactor_export_h5m.py

Refactoring the method of making the graveyard so that it can be centered around the center of the geometry
Reactor.export_dagmc_h5m(filename="dagmc.h5m", include_graveyard={'offset':10})
Reactor.export_dagmc_h5m(filename="dagmc.h5m", include_graveyard={'size':2000})

Centering graveyard when using offset

---

examples/example_parametric_reactors/render_of_random_reactor_render_gif.py
paramak/parametric_components/constant_thickness_dome.py
paramak/parametric_components/dished_vacuum_vessel.py
paramak/parametric_reactors/flf_system_code_reactor.py
paramak/parametric_reactors/negative_triangularity_reactor.py
paramak/reactor.py
paramak/shape.py
tests/test_parametric_reactors/test_flf_system_code_reactor.py
tests/test_parametric_shapes/test_extrude_mixed_shape.py

This PR removes the word "vacuum" from the name of components.
so componets like "vacuum_vessel" have been renamed "vessel"
This is useful as the name of components is used when making DAGMC tags
DAGMC tags including the word vacuum anywhere in the tag will treat the material as a vacuum. 
https://github.com/svalinn/DAGMC/issues/805#issuecomment-1104291031

removed vacuum from name

---

README.md
conda/meta.yaml
paramak/__init__.py
pyproject.toml
setup.cfg

added __version__ to package

---

paramak/reactor.py

now using assembly objects with cadquery jupyter,

Exporting assembly to html (allows explode view)

---

LICENSE.txt
paramak/parametric_components/constant_thickness_dome.py
paramak/parametric_components/poloidal_field_coil_case_set.py
paramak/utils.py

refactor exporting to h5m to work with updated downstream api changes

refactor exporting to h5m 

---

environment.yml
tests/tests_h5m/test_reactor_export_h5m.py

making use of Pytest instead of unit test can simplify the test scripts. I've converted one test script to make use of pytest and pytest fixtures instead of unittest to see how it looks

Pytest instead of unit test

---

docs/source/API-Reference.rst

just a little tidy up for the docs

[skip ci] moved reactor in api docs

---

Dockerfile
gui.Dockerfile

USage of setuptools_scm within docker no longer has access to the .git folder and therefore has trouble finding the version
setting the ```paramak_version``` is the work around
as advised in the [docs](https://github.com/pypa/setuptools_scm/blob/main/README.rst#usage-from-dockerZ)
It looks like "develop" is no longer an acceptable version number so I've changed it to "1.0.0"

Fixing pip install . in ci
