fusion-energy/paramak

.github/workflows/dockerhub-publish-dependencies.yml, .github/workflows/dockerhub-publish-dev.yml, .github/workflows/dockerhub-publish-geometry-dependencies.yml, .github/workflows/dockerhub-publish-stable.yml, README.md
=> updated links to new repo

.circleci/config.yml, .github/workflows/docker_ci_develop.yml, .github/workflows/docker_ci_main.yml, .github/workflows/dockerhub-publish-dependencies.yml, .github/workflows/dockerhub-publish-dev.yml, .github/workflows/dockerhub-publish-geometry-dependencies.yml, .github/workflows/dockerhub-publish-stable.yml, README.md, docs/source/index.rst, docs/source/paramak.install.rst
making use of github container registry instead of dockerhub
=> moving to github container registry

docs/source/paramak.parametric_shapes.rst
Added example shapes that can be view in the documents
=> updated docs

.github/workflows/docker_ci_develop.yml, docs/source/paramak.install.rst
improves docs for the install section
stops tirggering ci testing when on the docs or readme changes
=> clearer install instructions

.github/workflows/ci_with_install.yml, Dockerfile, environment.yml, setup.py
just removing some installs that were not needed and bumping the version
=> Fix ci again

README.md
This adds a few badges to the readme for CI, docker image publishing and code inspector
=> Adding code inspector badge

docs/source/paramak.parametric_components.rst, paramak/__init__.py, paramak/parametric_components/extrude_rectangle.py, tests/test_parametric_components/test_ExtrudeRectangle.py
Adds a new parametric shape which is just an extruded rectangle. It takes width and height like the PF coils shape
=> added rectangular extrusion

paramak/make_faceteted_neutronics_model.py, paramak/utils.py
Thanks for spotting this erorr @billingsley-john .
I have had a go at fixing it but this PR could do with a check
=> added make faceteted back

README.md
The badges currently point to the latest github action. These fail from time to time while we work on PRs. So it is best if they point to main branch
=> added branch main to badges

paramak/parametric_components/inner_tf_coils_flat.py, tests/test_parametric_components/test_InnerTfCoilsFlat.py
This adds an option to the InnerTfCoilsFlat that allows the inner_radius and outer_radius to be specified as the distance between the center point and the corner of the front surface or the straight part of the straight surface.
=> Tidy up vertical inner tf coils args

paramak/utils.py
Small updates to fix cubit integration - updated filepath and coreform_cubit run command flag
=> Fix cubit integration

paramak/parametric_components/blanket_fp.py, paramak/parametric_components/blanket_poloidal_segment.py, paramak/parametric_components/capsule_vacuum_vessel.py, paramak/parametric_components/center_column_circular.py, paramak/parametric_components/center_column_cylinder.py, paramak/parametric_components/center_column_flat_top_hyperbola.py, paramak/parametric_components/center_column_plasma_dependant.py, paramak/parametric_components/cutting_wedge_fs.py, paramak/parametric_components/inner_tf_coils_circular.py, paramak/parametric_components/inner_tf_coils_flat.py, paramak/parametric_components/poloidal_field_coil_case_set_fc.py, paramak/parametric_components/tf_coil_casing.py, paramak/parametric_components/toroidal_field_coil_coat_hanger.py, paramak/parametric_components/toroidal_field_coil_round_corners.py, paramak/parametric_components/vacuum_vessel.py, paramak/parametric_components/vacuum_vessel_inner_leg.py, paramak/parametric_reactors/segmented_blanket_ball_reactor.py, paramak/parametric_reactors/single_null_ball_reactor.py, paramak/parametric_reactors/single_null_submersion_reactor.py, paramak/parametric_reactors/sparc_paper_2020.py, paramak/reactor.py, paramak/shape.py, paramak/utils.py, setup.py
With python 3.6 and above f string are supported. Inspired by recent PR on OpenMC.
This PR replaces some .formats and adds a minimal python version to the setup.py
I also added a bit more type hinting
=> F strings instead of format

docs/source/paramak.parametric_components.rst, docs/source/paramak.parametric_reactors.rst, docs/source/paramak.parametric_shapes.rst
Some of the sections of components are quite large now, this PR is an attempt to separate up the docs into sub sections for parametric components
=> first attempt at submenus

paramak/make_faceteted_neutronics_model.py, paramak/parametric_reactors/ball_reactor.py, paramak/parametric_reactors/center_column_study_reactor.py, paramak/parametric_reactors/eu_demo_2015_reactor.py, paramak/parametric_reactors/submersion_reactor.py, paramak/reactor.py, paramak/shape.py, paramak/utils.py, tests/test_Reactor.py, tests/test_utils.py
This PR renames trelis to cubit across most of the package.
The one exception is the exporting of a "trelis" file from the make faceted  geometry. This needs further checking to see what the new equivalent is
=> replaced trelis with cubit

.github/workflows/python-publish.yml
The previous python publish did not work and it appears ```sed``` command needs to be changed a bit 
failed github action is here https://github.com/fusion-energy/paramak/actions/runs/1165540089
solution is here https://stackoverflow.com/questions/9366816/sed-fails-with-unknown-option-to-s-error
=> using new char for sed cmd

.circleci/config.yml, .github/workflows/test_demos.yml, run_tests.sh, tests/test_example_components.py, tests/test_example_reactors.py, tests/test_example_shapes.py
=> Added new workflow to test examples

Dockerfile
Thanks to @RemDelaporteMathurin for spotting this error and for raising issue #69 
This small change to the dockerfile should fix the problem of not loading the jupyter interface
=> corrected cmd command

paramak/__init__.py, paramak/parametric_reactors/cylinder_reactor.py, tests/test_parametric_reactors/test_cylinder_reactor.py
Adds a simplified reactor design. This is a really basic cylinder design. Also adds a few basic tests for file creation.
=> Adding inertial confinement model

CITATION.cff, Dockerfile, README.md, paramak/parametric_reactors/cylinder_reactor.py, paramak/reactor.py, paramak/shape.py, requirements-test.txt, setup.py, tests/test_parametric_components/test_ToroidalFieldCoilCoatHanger.py
Adds a citation file and moves the testing packages into a txt file and a few code inspector comments
=> Adding names to reactor

docs/source/paramak.parametric_components.rst
Adds a few more 3d models to the docs
=> Adding pf coils to docs

.github/workflows/ci_with_docker_build.yml, .github/workflows/ci_with_install.yml
This PR adds some ```path-ignores``` files and folders so that CI with testing does not run when simple changes are made to docs and other non source code files
=> avoid trigger ci when specific files change

paramak/parametric_components/extrude_hollow_rectangle.py, paramak/parametric_components/poloidal_field_coil_case.py, paramak/parametric_components/poloidal_field_coil_case_fc.py, paramak/parametric_shapes/extruded_mixed_shape.py, paramak/reactor.py
This PR will make hollow shapes differently so the are compatible with meshing
solving #152
Work in progress on this PR
=> Refactoring hollow unmeshable components with overlapping edges

.github/workflows/python-publish.yml
Checks that the `dist/` directory is suitable for publishing before calling `twine upload`.
Closes https://github.com/fusion-energy/paramak/issues/133
=> Added twine check line to python-publish

.github/workflows/ci_with_docker_build.yml, .github/workflows/ci_with_install.yml
Rather than selecting which paths to ignore when triggering CI, instead trigger only when certain files are changed.
Closes issue https://github.com/fusion-energy/paramak/issues/132
=> Trigger CI on certain paths rather than paths-ignore

.circleci/config.yml, .github/workflows/ci_with_install.yml, conda/meta.yaml, paramak/parametric_components/blanket_constant_thickness_arc_v.py, paramak/parametric_components/blanket_fp.py, paramak/parametric_components/center_column_circular.py, paramak/parametric_components/extrude_rectangle.py, paramak/parametric_components/poloidal_field_coil.py, paramak/parametric_components/port_cutters_rotated.py, paramak/parametric_components/shell_fs.py, paramak/parametric_components/tf_coil_casing.py, paramak/parametric_components/vacuum_vessel_inner_leg.py, paramak/reactor.py, paramak/shape.py
Just a few tiny improvements to the code, removed a few unused import statements and a few typos
=> typos and unused imports

.circleci/config.yml, .github/workflows/ci_with_install.yml, conda/meta.yaml, paramak/parametric_components/blanket_constant_thickness_arc_v.py, paramak/parametric_components/blanket_fp.py, paramak/parametric_components/center_column_circular.py, paramak/parametric_components/extrude_rectangle.py, paramak/parametric_components/poloidal_field_coil.py, paramak/parametric_components/port_cutters_rotated.py, paramak/parametric_components/shell_fs.py, paramak/parametric_components/tf_coil_casing.py, paramak/parametric_components/vacuum_vessel_inner_leg.py, paramak/reactor.py, paramak/shape.py
Reverting accidental merge to main
=> Revert "typos and unused imports"

.circleci/config.yml, .github/workflows/ci_with_install.yml, conda/meta.yaml, paramak/parametric_components/blanket_constant_thickness_arc_v.py, paramak/parametric_components/blanket_fp.py, paramak/parametric_components/center_column_circular.py, paramak/parametric_components/extrude_rectangle.py, paramak/parametric_components/poloidal_field_coil.py, paramak/parametric_components/port_cutters_rotated.py, paramak/parametric_components/shell_fs.py, paramak/parametric_components/tf_coil_casing.py, paramak/parametric_components/vacuum_vessel_inner_leg.py, paramak/reactor.py, paramak/shape.py
Fixed the ci, removed unused imports
=> Minor fixes

.github/workflows/anaconda-publish-develop.yml
iny pr to correct the channel order
=> [skip ci] corrected conda channel order

.github/workflows/anaconda-publish-develop.yml, conda_dev/meta.yaml
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
=> Updating conda Dev action

docs/source/example_parametric_components.rst, docs/source/example_parametric_reactors.rst, docs/source/example_parametric_shapes.rst, docs/source/index.rst, docs/source/tests.rst
updated documentation links to fusion-energy rather than UKAEA versions so that any changes made are reflected in the documentation links.  This is including example notebooks, CI links etc, but not including links to documents completed under UKAEA e.g. pullrequest report.
There is still one broken link on the index page to the arc reactor paper, but I cannot find the correct link. @shimwell if you can supply the correct link or edit directly
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your …
=> Docs update

CITATION.cff
@py1sl we have CITATION.cff files in most repos. Feel free to add yourself and orcid if you have one? The file is used by Github to make a bibtex citation automatically. This is available via the cite this repository button on the right hand side.
=> added @py1sl to citation

.github/workflows/test_demos.yml
just adding some exclusions to running the test demos ci, nothing major
=> added trigger paths to test demos ci

docs/source/install.rst
Adding details of how to use mamba for the install
=> added mamba as recommended route

docs/source/install.rst
Adds versions to the install instructions
=> added version pin to install instructions

.github/workflows/anaconda-publish.yml, .github/workflows/conda-build-test.yml, conda/conda_build_config.yaml, conda/meta.yaml, paramak/parametric_components/extrude_hollow_rectangle.py, setup.cfg
Adding a missing argument to box sections ```extrusion_start_offset```
=> adding adding_extrusion_start_offset arg to componet

examples/example_parametric_reactors/render_of_random_reactor_render_with_text_gif.py
=> added text on render example

src/paramak/parametric_components/dished_vacuum_vessel.py
attempt to fix bug reported in issue #270
=> compound instead of union

docs/source/conf.py
replaces #273
just a small PR to see if the version numbers can be automatically found
=> Adding version automatically to docs

tests/tests_units/test_parametric_components/test_vacuum_vessel.py
just making a test simpler to use as an example test for other devs
=> Pytest makes more concise tests

src/paramak/reactor.py, src/paramak/shape.py, src/paramak/utils.py
to help debug h5m exports this pr passes a verbose flag down the toolchain
=> Passing verbose flag to dagmc export

Dockerfile, conda/meta.yaml, gui.Dockerfile, pyproject.toml
this updates the version of cad_to_dagmc to make sure our api usage (with tolerances) is correct
=> moved to cad-to-dagmc version 0.2.0

pyproject.toml
Just pinning the version of sphinx to help get the docs building again
=> pinned sphinx version
